Repository HewlettPackard/ODIM, pull requests merged in 2020-10, with the labels that each got.

#11 changed the name of the library to lib-rest-client
  .github/workflows/build_deploy_test.yml
  .github/workflows/build_unittest.yml
  build/odimra/makedep.sh
  lib-rest-client/README.md
  lib-rest-client/go.mod
  lib-rest-client/go.sum
  lib-rest-client/pmbhandle/rest.go
  lib-utilities/common/constants.go
  lib-utilities/common/pluginstatus_test.go
  lib-utilities/config/config.go
  lib-utilities/config/config_test.go
  lib-utilities/config/odimra_config.json
  svc-aggregation/agmodel/system.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/aggregator_test.go
  svc-aggregation/rpc/common.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/common.go
  svc-aggregation/system/connectionmethods.go
  svc-aggregation/system/connectionmethods_test.go
  svc-aggregation/system/rediscoverinventory.go
  svc-api/go.mod
  svc-api/go.sum
  svc-api/handle/aggregator.go
  svc-api/handle/aggregator_test.go
  svc-api/handle/handlers_test.go
  svc-api/models/serviceroot.go
  svc-api/router/router.go
  svc-api/rpc/aggregator.go
Labels: enhancement

#13 changing the imports from the svc-plugin-rest-client to lib-rest-client
  .github/workflows/build_unittest.yml
  build/odimra/build.sh
  build/odimra/builddep.sh
  lib-utilities/common/dbconn.go
  lib-utilities/config/config_test.go
  svc-aggregation/agcommon/common.go
  svc-aggregation/agmodel/system.go
  svc-aggregation/agresponse/rpc.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/main.go
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/aggregator_test.go
  svc-aggregation/rpc/common.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/connectionmethods.go
  svc-aggregation/system/connectionmethods_test.go
  svc-api/handle/aggregator.go
  svc-api/handle/aggregator_test.go
  svc-api/handle/handlers_test.go
  svc-api/router/router.go
  svc-api/rpc/aggregator.go
  svc-events/evcommon/common.go
  svc-events/events/publishevttosubscriber.go
  svc-events/go.mod
  svc-events/go.sum
  svc-events/main.go
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-fabrics/main.go
  svc-managers/go.mod
  svc-managers/go.sum
  svc-managers/managers/common.go
  svc-systems/chassis/getresource.go
  svc-systems/chassis/getresource_test.go
  svc-systems/go.mod
  svc-systems/go.sum
  svc-systems/rpc/chassis.go
  svc-systems/rpc/systems.go
  svc-systems/systems/storage.go
  svc-update/go.mod
  svc-update/go.sum
  svc-update/update/common.go
Labels: enhancement

#15 Clean up and refactor in lib-utilities for the CreateGenericErrorResponse function
  lib-utilities/response/errorresponse.go
  lib-utilities/response/errorresponse_test.go
Labels: bug

#17 Issue 161
  lib-dmtf/go.mod
  lib-dmtf/go.sum
  lib-persistence-manager/go.mod
  lib-persistence-manager/go.sum
  lib-rest-client/go.mod
  lib-rest-client/go.sum
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/bootorder.go
  svc-aggregation/system/common.go
  svc-aggregation/system/update_test.go
  svc-api/go.mod
  svc-api/go.sum
  svc-events/events/submittestevent.go
  svc-events/go.mod
  svc-events/go.sum
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-managers/go.mod
  svc-managers/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
  svc-task/go.mod
  svc-task/go.sum
  svc-update/go.mod
  svc-update/go.sum
  svc-update/update/simpleUpdate.go
  svc-update/update/simpleUpdate_test.go
Labels: bug

#18 syncing latest changes from the upstream
  lib-utilities/response/errorresponse.go
  lib-utilities/response/errorresponse_test.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/bootorder.go
  svc-aggregation/system/common.go
  svc-aggregation/system/update_test.go
  svc-events/events/submittestevent.go
Labels: enhancement

#19 Issue 172
  lib-utilities/services/auth.go
  svc-account-session/session/create.go
  svc-api/main.go
Labels: enhancement

#21 Odim 3597:Saving ip in place of FQDN for device subscription data for Fabric event subscriptions
  svc-events/events/evtsubscription.go
Labels: bug

#22 Odim 3631:Using the ip instead of fqdn in delete event subscription
  svc-events/events/deletesubscription.go
  svc-events/events/getevtsubscription_test.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
Labels: bug

#24 Issue 172
  lib-utilities/go.mod
  lib-utilities/go.sum
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-api/go.mod
  svc-api/go.sum
  svc-events/go.mod
  svc-events/go.sum
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-managers/go.mod
  svc-managers/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
  svc-task/go.mod
  svc-task/go.sum
  svc-update/go.mod
  svc-update/go.sum
Labels: enhancement

#25 odim 3650:Refactoring the network look up code
  svc-events/events/deletesubscription.go
  svc-events/events/evtsubscription.go
Labels: bug

#26 Issue 197
  svc-events/events/deletesubscription.go
  svc-events/events/evtsubscription.go
  svc-events/events/getevtsubscription_test.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
  svc-systems/rpc/systems.go
Labels: bug

#27 Issue 200: GRF plugin has "bios" instead of "Bios" in route
  plugin-redfish/main.go
Labels: bug

#28 Issue 201: GET on individual Storage, Drives and Volumes not defined in Generic Redfish Plugin
  plugin-redfish/main.go
Labels: bug

#29 Fix for issue-200 and issue-201
  plugin-redfish/main.go
Labels: bug

#31 Issue 157
  README.md
Labels: documentation

#32 Issue 205 fix for 3422
  svc-managers/managers/common.go
  svc-managers/managers/common_test.go
  svc-managers/managers/managers.go
  svc-managers/managers/managers_test.go
  svc-managers/mgrmodel/manager.go
  svc-managers/mgrmodel/manager_test.go
  svc-managers/rpc/manager_test.go
Labels: enhancement
